name: Release (Portable)

on:
  push:
    branches: [ main ]
    tags:
      - app-v*
  workflow_dispatch:

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    name: Build (${{ matrix.platform }})
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, ubuntu-22.04]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20.4.x"
          cache: "yarn"

      # Linux GUI deps required by Tauri even for portable "app" target
      - name: Install Linux build deps
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev libwebkit2gtk-4.0-dev \
            libappindicator3-dev librsvg2-dev patchelf file coreutils

      - uses: dtolnay/rust-toolchain@stable

      - name: Install JS deps
        run: yarn --immutable

      - name: Build workspace
        run: yarn build
        env:
          NODE_OPTIONS: --max-old-space-size=6000

      # Build ONLY portable executables and DISABLE updater (no signing keys needed)
      - name: Build Tauri App (portable, no updater)
        uses: tauri-apps/tauri-action@v0
        with:
          projectPath: packages/app
          tauriScript: yarn tauri
          # IMPORTANT: no extra "build" token; the action runs `tauri build` already.
          # Compact JSON to avoid quoting issues.
          args: >-
            --verbose
            --config {"tauri":{"updater":{"active":false},"bundle":{"targets":["app"]}}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_OPTIONS: --max-old-space-size=6000

      # Stage ONLY the final executable per-OS and archive it with a clean name
      - name: Stage portable binary (Windows)
        if: matrix.platform == 'windows-latest'
        shell: pwsh
        run: |
          Set-StrictMode -Version Latest
          $ErrorActionPreference = "Stop"
          New-Item -ItemType Directory -Force -Path dist | Out-Null
          # pick the newest .exe from Tauri release outputs
          $exe = Get-ChildItem -Path "packages\app\src-tauri\target" -Recurse -Filter *.exe `
                  | Where-Object { $_.FullName -match '\\release\\' } `
                  | Sort-Object LastWriteTime -Descending | Select-Object -First 1
          if (-not $exe) { throw "No portable .exe found under src-tauri\target\*\release" }
          Copy-Item $exe.FullName dist\rivet-windows-latest.exe -Force
          Compress-Archive -Path dist\rivet-windows-latest.exe -DestinationPath dist\rivet-windows-latest.zip -Force

      - name: Stage portable binary (Linux)
        if: matrix.platform == 'ubuntu-22.04'
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p dist
          # Find ELF executable(s) under release; pick the largest one (usually the app)
          bin="$(find packages/app/src-tauri/target -type f -path '*/release/*' \
                   -exec sh -c 'file -b "$1" | grep -q "ELF" && printf "%s %s\n" "$(stat -c%s "$1")" "$1"' sh {} \; \
                   | sort -nr | head -n1 | awk '{ $1=""; sub(/^ /,""); print }')"
          if [ -z "${bin:-}" ] || [ ! -f "$bin" ]; then
            echo "No ELF executable found under src-tauri/target/**/release" >&2
            exit 1
          fi
          cp -v "$bin" dist/rivet-ubuntu-22.04
          tar -czf dist/rivet-ubuntu-22.04.tar.gz -C dist rivet-ubuntu-22.04

      - name: Upload portable artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rivet-${{ matrix.platform }}
          path: |
            dist/rivet-windows-latest.zip
            dist/rivet-ubuntu-22.04.tar.gz
          if-no-files-found: error
          retention-days: 30
          compression-level: 6

  publish:
    name: Publish release assets
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: _artifacts

      - name: List gathered files
        run: |
          echo "Collected files:"
          find _artifacts -type f -maxdepth 6 -print

      # Nightly prerelease for main/manual runs (same tag each time → updated assets)
      - name: Publish Nightly prerelease (portable)
        if: ${{ !startsWith(github.ref, 'refs/tags/app-v') }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: nightly
          name: Nightly
          prerelease: true
          draft: false
          fail_on_unmatched_files: true
          generate_release_notes: false
          files: |
            _artifacts/**/rivet-windows-latest.zip
            _artifacts/**/rivet-ubuntu-22.04.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Versioned Draft Release for tags app-v*
      - name: Publish versioned release (draft, portable)
        if: startsWith(github.ref, 'refs/tags/app-v')
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          name: Rivet IDE ${{ github.ref_name }}
          body: |
            Portable builds (no installer). Download the asset for your platform.
          fail_on_unmatched_files: true
          files: |
            _artifacts/**/rivet-windows-latest.zip
            _artifacts/**/rivet-ubuntu-22.04.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
